### ISSUE TITLE
Fix stopwatch restart 

### ISSUE THREAD

**Issue by swagatmitra-b** [swagatmitra-b/Productivity-App#1]
On clicking the "Stop" button in the stopwatch page while the stopwatch is running and then clicking the "Start" button right after, the stopwatch resets and begins from 0. The stopwatch should continue from the same timestamp when it stopped after the "Stop" button was first pressed.

**Comment by Hrx4** [comment]
Hey assign me the issue , i can fix this

**Comment by deepanshu0304** [comment]
Hi! I will be able to fix this issue. Please assign this task to me.
