### ISSUE TITLE
Fix note selection on initial load

### ISSUE THREAD

**Issue by swagatmitra-b** [swagatmitra-b/Productivity-App#2]
When the notes page loads initially and the user clicks on a note that was previously saved, the content of the note is not rendered on the right hand view panel. The note selection only works correctly from the second click onwards.

**Comment by Br0k3nh4nd012** [comment]
@swagatmitra-b Can I take this?

**Comment by Br0k3nh4nd012** [comment]
@swagatmitra-b Please take a look at the [PR](https://github.com/swagatmitra-b/Productivity-App/pull/6).

**Comment by Br0k3nh4nd012** [comment]
@swagatmitra-b I have a question. I can see that, you have approved the PR. But can I know why it is still not merged?

**Comment by swagatmitra-b** [comment]
If you are intending to participate for Hacktoberfest, which is what I assume, only PRs merged on October will be counted.
