### ISSUE TITLE
Blank note render on note creation

### ISSUE THREAD

**Issue by swagatmitra-b** [swagatmitra-b/Productivity-App#5]
When a new note is created by clicking the new note button, the right hand view panel does not automatically render the blank note on creation. Instead, it does so when the note is clicked.

**Comment by debsouryadatta** [comment]
@swagatmitra-b please assign me this issue✌️

**Comment by blazenn2** [comment]
@swagatmitra-b 
Hi

I am available to solve this issue ... could u please assign me so that I can start working on it? Many thanks in advance.
